
from colorama import Fore as F

def aboutGame():
	print(F.RED+"THIS IS A GAME\nWHERE YOU PLAY\nROCK-PAPER-SCISSORS GANE\nYOU CHOOSE YOUR OPTION\nAFTER THAT COMPUTER CHOOSE THEIR OPTION\nAND ITS COMPLETELY RAMDOM")
	print(F.CYAN+"GAME RULE\nROCK BEATS SCISSORS\nSCISSORS BEATS PAPER\nPAPER BEATS ROCK\nIF YOU CHOSE ROCK\nAND COMPUTER CHOSE SCISSORS\nTHEN")

if __name__ == "__main__":
	aboutGame()