
from colorama import Fore as F

def aboutGame():
	print(F.RED+"THIS IS A GAME\nWHERE YOU PLAY\nROCK-PAPER-SCISSORS GANE\nYOU CHOOSE YOUR OPTION\nAFTER THAT COMPUTER CHOOSE IT'S OPTION\nAND ITS COMPLETELY RAMDOM")
	print(F.CYAN+"GAME RULE\nROCK BEATS SCISSORS\nSCISSORS BEATS PAPER\nPAPER BEATS ROCK")

if __name__ == "__main__":
	aboutGame()